steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}
      - --tag=gcr.io/${PROJECT_ID}/${REPO_NAME}:latest
      - --file=Dockerfile
      - .
images:
  - gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}
  - gcr.io/${PROJECT_ID}/${REPO_NAME}:latest
